// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SettlementService.Infrastructure.Persistent;

#nullable disable

namespace SettlementService.Infrastructure.Persistent.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241208022109_initialize")]
    partial class initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SettlementService.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.ComplexProperty<Dictionary<string, object>>("BookingTime", "SettlementService.Domain.Entities.Booking.BookingTime#BookingTime", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Hour")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Time")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("BookingId");

                    b.ToTable("Booking", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
